# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MunchBunch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MunchBunch
  pod 'Alamofire', '~> 4.5'
  pod 'FontAwesomeKit/FontAwesome'
  pod 'SwiftyJSON'
  pod 'SwiftyBeaver'
  pod 'Validator'
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git', :branch => 'wip/swift4'
end
